#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

runcmd:
    - systemctl enable aws-env
    - systemctl enable porters-hostname.service
    - systemctl enable amazon-cloudwatch-agent